### ISSUE TITLE
Direct to Comment Link... Can't Pull the ID

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/Glancer#6]
The end resulting link Shows Task in url and also displays task which is fine but not ideal...
https://github.com/aljawaid/Glancer/blob/84db232275e26a9158db8aba4384e1bc6dd1f201/Controller/TaskCommentViewController.php#L25

My Version for Direct to comment
`$this->response->redirect($this->helper->url->to('TaskCommentViewController', 'showTask', array('plugin' => 'Glancer', 'task_id' => $task_id), 'comment-'$commentID), true);`

Notice the 'comment-'$commentID` as I'm trying to result in...
`https://my.company.com/project/37/task/476#comment-3754` which is how the current default 'link to comment' in the comment dropdown works. (It goes direct to show the comment within the task on enter)

I thought maybe I would need to add a route but I got confused as when it shows the commentID-searched task, its a nice task pretty url... so very confused on this one.

Any input please?

**Comment by creecros** [comment]
you need to edit this route.
https://github.com/aljawaid/Glancer/blob/84db232275e26a9158db8aba4384e1bc6dd1f201/Plugin.php#L23

instead of `task/:task_id`
use `project/:project_id/task/:task_id/#comment-:comment_id`

just note everything with a : is a, `:variable`

and currently, only :task_id will be recognized. 

which is where you need to add the other variables here
https://github.com/aljawaid/Glancer/blob/84db232275e26a9158db8aba4384e1bc6dd1f201/Controller/TaskCommentViewController.php#L25

make sure they are inside the array, in your example above, you added comment_id outside the array. you will also need project ID, make sure you define it first.

**Comment by aljawaid** [comment]
Great I will work on this tonight and get back to you

**Comment by creecros** [comment]
This is the normal link for a comment:
![image](https://user-images.githubusercontent.com/26339368/199242371-73a4683a-f3a4-46c6-b2a1-4a1608e15e64.png)

so it has to be that, or it won't work.
